[project]
name = "prpc-flask"
version = "0.1.0"
description = "Flask adapter for pRPC"
requires-python = ">=3.11"
dependencies = [
    "prpc",
    "flask>=3.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/prpc_flask"]
